version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: stockwell/atari-vcs-emu:0.0.1

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: ./build.sh
      - codecov/upload:
          file: cmake-build-docker/atari-2600-tests/xml_coverage.xml
