version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: gcc:latest

    steps:
      - run:
          name: Install Dependencies
          command: |
              apt-get -y -q update
              apt-get -y -q install cmake gcovr
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: ./build.sh
      - codecov/upload:
          file: cmake-build-docker/emulator-tests/coverage.xml
      - store_test_results:
          path: cmake-build-docker/emulator-tests
